version: '3.7'
services:
  backend:
    build: backend
    command: gunicorn app.main:app -w 1 -k uvicorn.workers.UvicornWorker --bind=0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - ./docker/backend/data/data.json:/data.json
  frontend:
    build: frontend
    command: npm start
    ports:
      - 80:5000
